### ISSUE TITLE
Adding chat

### ISSUE THREAD

**Issue by RoySegall** [RoySegall/bargain#8]
* [x] The chat will be based on normal entities(#46):
  * Chat room:
    * Owner
    * Guest
  * Chat messages
    * Text
    * Sender
    * Status: sent or read
After that the steps are:
* [x] Displaying the rooms. The user can only have access to rooms which he created or a guest of one of them(#47).
* [x] Endpoint to see the messages in a room (#48)
* [x] Endpoint to add messages (#49)
* [x] Pusher integration
